# Generated by Django 5.0.3 on 2024-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('Tata', 'Tata'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], max_length=255)),
                ('fuel_name', models.ManyToManyField(to='app.fueltypemodel')),
            ],
        ),
    ]
